axf/urls.py
from django.conf.urls import url

from axf import views

urlpatterns =[
    url(r'^$',views.home,name='index'),
    url(r'^home/$',views.home,name='home'),
    url(r'^cart/$',views.cart,name='cart'), #gouwuche
    url(r'^market/(\d+)/(\d+)/(\d+)/$',views.market,name='market'), #闪购超市
    url(r'^mine/$',views.mine,name='mine'),#我的

    url(r'^registe/$',views.registe,name='registe'),#注册
    url(r'^checkaccount/$',views.checkaccount,name='checkaccount'),#验证
    url(r'^logout/$', views.logout, name='logout'),#登出
    url(r'^login/$', views.login, name='login'),#登录

    url(r'^addcart/$',views.addcart,name='addcart'),  #添加购物车
    url(r'^subcart/$',views.subcart,name='subcart'),    # 购物车减操作

    # 修改选中状态
    url(r'^changecartstatus/$',views.changecartstatus,name='changecartstatus'),
    # quanxuan 取消全选
    url(r'^changecartselect/$',views.changecartselect,name='changecartselect'),
]

py1809AXF/urls.py
from django.conf.urls import url,include
from django.contrib import admin
# from django.urls import path,

urlpatterns = [
    url('admin/', admin.site.urls),
    url('^',include('axf.urls',namespace='axf'))
]

templates/mine/login.html
{% extends 'base/base.html' %}
{% load static %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/login.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'mine/js/login.js' %}"></script>
{% endblock %}

{% block title %}
    爱鲜蜂 | 登录
{% endblock %}

{% block content %}
    <div class="login">
        <div class="back">
            <a href="{% url 'axf:mine' %}">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        </div>
     <form action="{% url 'axf:login' %}" method="post">
            {% csrf_token %}
            {#            账号#}
            <div class="form-group has-feedback" id="account">
                <div class="input-group">
                    <div class="input-group-addon">账号</div>
                    <input type="text" class="form-control" placeholder="数字、字母" name="account" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i>{{ acountErr }}</i>
            </div>
         <div class="form-group" id="password">
                <div class="input-group">
                    <div class="input-group-addon">密码</div>
                    <input type="password" class="form-control" placeholder="6~12位纯数字" name="password" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i>{{ passwdErr }}</i>
            </div>
         <div id="subButton" class="btn btn-default">
                登录
            </div>
         </form>
        </div>
{% endblock %}

templates/mine/mine.html
{% extends 'base/base.html' %}
{% load static %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'mine/js/mine.js' %}" ></script>
{% endblock %}
{% block title %}
    mine
{% endblock %}


{% block content %}
    <div class="mine">
        <div class="user-wrapper">
            <div class="user-img">
                <img src="{{ img  }}" alt="">
            </div>
            <div class="user-content">
                <p><a href="{% url 'axf:login' %}"><span class="glyphicon glyphicon-user"></span></a>{{ name }}</p>
                <p><span class="glyphicon glyphicon-certificate "></span>{{ rank | default:'暂无等级' }}</p>
                <a href="{% url 'axf:registe' %}" class="register">注册</a>
            </div>
        </div>
        <div class="collect">
            <span class="glyphicon glyphicon-link"></span>
            <i>收藏</i>
        </div>
        <div class="other">
            <section class="my">
                <span>我的订单</span>
                <a href="#">查看订单 <b class="glyphicon glyphicon-chevron-right"></b></a>
            </section>
            <section>
                <ul>
                    <li>
                        <a href="#">
                            <dl class="item">
                                <dt>
                                    <span class="glyphicon glyphicon-gift"></span>
                                </dt>
                                <dd>待付款</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl class="item">
                                <dt>
                                    <span class="glyphicon glyphicon-leaf"></span>
                                </dt>
                                <dd>待收货</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl class="item">
                                <dt>
                                    <span class="glyphicon glyphicon-fire"></span>
                                </dt>
                                <dd>待评价</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl class="item">
                                <dt>
                                    <span class="glyphicon glyphicon-magnet"></span>
                                </dt>
                                <dd>退款/售后</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </section>
            <section>
                <ul>
                    <li>
                        <a href="#">
                            <dl >
                                <dt>
                                    <span class="glyphicon glyphicon-thumbs-down"></span>
                                </dt>
                                <dd>优惠券</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl >
                                <dt>
                                    <span class="glyphicon glyphicon-hand-right"></span>
                                </dt>
                                <dd>收货地址</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl >
                                <dt>
                                    <span class="glyphicon glyphicon-hand-left"></span>
                                </dt>
                                <dd>客户反馈</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl >
                                <dt>
                                    <span class="glyphicon glyphicon-hand-left"></span>
                                </dt>
                                <dd>关于我们</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </section>


            {% if isLogin %}
                 <section class="quit">
                <a href="{%  url 'axf:logout' %}">退出</a>
            </section>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/mine/registe.html
{% extends 'base/base.html' %}
{% load static %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/register.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'mine/js/registe.js' %}"></script>
{% endblock %}

{% block title %}
    爱鲜蜂 | 注册
{% endblock %}
{% block content %}
    <div class="register">
        <div class="back">
            <a href="{% url 'axf:mine' %}">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        </div>
{#        zhanghao#}
        <form action="{% url 'axf:registe'  %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="from-group">
                <div class="input-group">
                    <div class="input-group-addon">账号</div>
                    <input type="text" class="form-control" placeholder="数字、字母" name="account" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i></i>
            </div>
{#            mima#}
            <div class="form-group" id="password">
                <div class="input-group">
                    <div class="input-group-addon">密码</div>
                    <input type="password" class="form-control" placeholder="6~12位纯数字" name="password" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i></i>
            </div>
{#            mima#}
            <div class="form-group" id="passwd">
                <div class="input-group">
                    <div class="input-group-addon">密码</div>
                    <input type="password" class="form-control" placeholder="6~12位" name="passwd" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i></i>
            </div>
{#            name#}
             <div class="form-group" id="name">
                <div class="input-group">
                    <div class="input-group-addon">名字</div>
                    <input type="text" class="form-control" placeholder="名字" name="name" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i></i>
            </div>
{#            tel#}
            <div class="form-group" id="phone">
                <div class="input-group">
                    <div class="input-group-addon">手机</div>
                    <input type="text" class="form-control" placeholder="11位" name="phone" required="required">
                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                </div>
                <i></i>
            </div>
{#            addr#}
             <div class="form-group" id="addr">
                <div class="input-group">
                    <div class="input-group-addon">地址</div>
                    <input type="text" class="form-control" placeholder="收货地址(默认选项)" name="addr" required="required">
                </div>
            </div>
{#            icon#}
               <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon">头像</div>
                    <input type="file" name="icon" required="required">
                </div>
            </div>
             <input type="submit" id="subButton" value="注册">
        </form>
    </div>
{% endblock %}